using System;using System.Data;using System.Data.SqlClient;using System.Collections.Generic;namespace RealEstate.DataAccess{	public class Support	{		#region[Declare variables]		private string  _Id;		private string  _Name;		private string  _Tel;		private string  _Type;		private string  _Nick;		private string  _Ord;		private string  _Active;		private string  _GroupSupportId;		private string  _Lang;
        private string _Location;

       		#endregion		#region[Public Properties]		public string Id{ get { return _Id; } set { _Id = value; } }		public string Name{ get { return _Name; } set { _Name = value; } }		public string Tel{ get { return _Tel; } set { _Tel = value; } }		public string Type{ get { return _Type; } set { _Type = value; } }		public string Nick{ get { return _Nick; } set { _Nick = value; } }		public string Ord{ get { return _Ord; } set { _Ord = value; } }		public string Active{ get { return _Active; } set { _Active = value; } }		public string GroupSupportId{ get { return _GroupSupportId; } set { _GroupSupportId = value; } }		public string Lang{ get { return _Lang; } set { _Lang = value; } }
        public string Location
        {
            get { return _Location; }
            set { _Location = value; }
        }		#endregion		#region[Support IDataReader]		public Support SupportIDataReader(IDataReader dr)		{			DataAccess.Support obj = new DataAccess.Support();			obj.Id = (dr["Id"] is DBNull) ? string.Empty : dr["Id"].ToString();			obj.Name = (dr["Name"] is DBNull) ? string.Empty : dr["Name"].ToString();			obj.Tel = (dr["Tel"] is DBNull) ? string.Empty : dr["Tel"].ToString();			obj.Type = (dr["Type"] is DBNull) ? string.Empty : dr["Type"].ToString();			obj.Nick = (dr["Nick"] is DBNull) ? string.Empty : dr["Nick"].ToString();			obj.Ord = (dr["Ord"] is DBNull) ? string.Empty : dr["Ord"].ToString();			obj.Active = (dr["Active"] is DBNull) ? string.Empty : dr["Active"].ToString();			obj.GroupSupportId = (dr["GroupSupportId"] is DBNull) ? string.Empty : dr["GroupSupportId"].ToString();			obj.Lang = (dr["Lang"] is DBNull) ? string.Empty : dr["Lang"].ToString();
            obj.Location = (dr["Location"] is DBNull) ? string.Empty : dr["Location"].ToString();			return obj;		}		#endregion	}}